<?php

/**
 * @file
 * Contains cnect_map.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function cnect_map_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the cnect_map module.
    case 'help.page.cnect_map':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Allows to use Webtools Map Service within Drupal') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function cnect_map_theme($existing, $type, $theme, $path) {
  return [
    'cnect_map' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * implements hook_preprocess_HOOK()
 */
function template_preprocess_cnect_map(&$variables) {
  $variables['#attached']['library'][] = 'cnect_map/smartloader';
  $variables['content'] = [];
  foreach (\Drupal\Core\Render\Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
  /** @var \Drupal\cnect_map\Entity\CnectMap $entity */
  $entity = $variables['elements']['#cnect_map'];
  $variables['settings'] = $entity->settings->value;
  //$variables['label'] = $entity->label();
  $variables['url'] = $entity->toUrl()->toString();
}
